from unittest.mock import patch, MagicMock

from sift.modules.agents.service import compile_and_save_agent


@patch("dspy.teleprompt.BootstrapFewShot")
@patch("sift.modules.agents.repository.langfuse.save_agent")
def test_compile_and_save_agent_preserves_signature_fields(
    mock_save_agent, mock_bootstrap
):
    # Prepare original fields exactly how a user would send them
    original_fields = [
        {"name": "input_a", "json_schema_extra": {"__dspy_field_type": "input"}},
        {"name": "input_b", "json_schema_extra": {"__dspy_field_type": "input"}},
        {"name": "output_c", "json_schema_extra": {"__dspy_field_type": "output"}},
    ]

    # Payload similar to what AgentRequest provides
    payload = {
        "agent_name": "test-agent",
        "agent_card_params": {},
        "litellm_params": {"model": "openai/gpt-4o-mini"},
        "dspy_params": {
            "state": {
                "main_predictor": {
                    "signature": {
                        "instructions": "Original instructions.",
                        "fields": original_fields,
                    },
                    "train": [{"input_a": "A", "input_b": "B", "output_c": "C"}],
                    "traces": [],
                    "demos": [],
                }
            }
        },
    }

    # Mock DSPy's BootstrapFewShot
    mock_optimizer = MagicMock()

    # We need a dummy compiled module whose dump_state looks like DSPy's output.
    # DSPy dump_state strips out field names/types.
    mock_compiled_module = MagicMock()
    mock_compiled_module.dump_state.return_value = {
        "main_predictor": {
            "signature": {
                "instructions": "Optimized instructions.",
                "fields": [
                    {"prefix": "Input A:", "description": "${input_a}"},
                    {"prefix": "Input B:", "description": "${input_b}"},
                    {"prefix": "Output C:", "description": "${output_c}"},
                ],
            },
            "train": [{"input_a": "A", "input_b": "B", "output_c": "C"}],
            "traces": [],
            "demos": [
                {"input_a": "A", "input_b": "B", "output_c": "C", "augmented": True}
            ],
            "lm": None,
        }
    }

    mock_optimizer.compile.return_value = mock_compiled_module
    mock_bootstrap.return_value = mock_optimizer

    # Act
    compile_and_save_agent(payload)

    # Assert
    from sift.modules.agents.metric import dynamic_api_metric
    mock_bootstrap.assert_called_once_with(metric=dynamic_api_metric)
    
    mock_save_agent.assert_called_once()
    saved_agent = mock_save_agent.call_args[0][0]

    # Verify the saved agent preserves the original fields list instead of DSPy's stripped version
    pred_state = saved_agent.dspy_params.state["main_predictor"]

    assert pred_state.signature.instructions == "Optimized instructions.", (
        "Instructions should be updated by DSPy."
    )
    assert pred_state.signature.fields == original_fields, (
        "Original rich fields should be preserved."
    )
    assert len(pred_state.demos) == 1, (
        "Demos generated by compilation should be captured."
    )


@patch("dspy.teleprompt.BootstrapFewShot")
@patch("sift.modules.agents.repository.langfuse.save_agent")
def test_compile_and_save_agent_no_trainset(mock_save_agent, mock_bootstrap):
    # Payload with no train examples
    original_fields = [
        {"name": "input_a", "json_schema_extra": {"__dspy_field_type": "input"}},
        {"name": "output_b", "json_schema_extra": {"__dspy_field_type": "output"}},
    ]

    payload = {
        "agent_name": "test-agent",
        "agent_card_params": {},
        "litellm_params": {"model": "openai/gpt-4o-mini"},
        "dspy_params": {
            "state": {
                "main_predictor": {
                    "signature": {
                        "instructions": "Do something.",
                        "fields": original_fields,
                    },
                    "train": [],
                    "traces": [],
                    "demos": [],
                }
            }
        },
    }

    compile_and_save_agent(payload)

    # BootstrapFewShot should not be called since there is no trainset
    mock_bootstrap.assert_not_called()

    mock_save_agent.assert_called_once()
    saved_agent = mock_save_agent.call_args[0][0]

    pred_state = saved_agent.dspy_params.state["main_predictor"]
    # Even without compilation, the signature should be preserved because dump_state is still called on the base module
    assert pred_state.signature.fields == original_fields
    assert pred_state.signature.instructions == "Do something."


@patch("sift.modules.agents.repository.langfuse.save_agent")
@patch("dspy.teleprompt.MIPROv2")
def test_compile_and_save_agent_dynamic_optimizer(mock_miprov2, mock_save_agent):
    payload = {
        "agent_name": "test-agent",
        "agent_card_params": {},
        "litellm_params": {"model": "openai/gpt-4o-mini"},
        "dspy_params": {
            "optimizer": "MIPROv2",
            "optimizer_params": {"num_candidates": 2},
            "state": {
                "main_predictor": {
                    "signature": {
                        "instructions": "Original instructions.",
                        "fields": [
                            {"name": "input_a", "json_schema_extra": {"__dspy_field_type": "input"}},
                            {"name": "output_c", "json_schema_extra": {"__dspy_field_type": "output"}},
                        ],
                    },
                    "train": [{"input_a": "A", "output_c": "C"}],
                    "traces": [],
                    "demos": [],
                }
            }
        },
    }

    mock_optimizer = MagicMock()
    mock_compiled_module = MagicMock()
    mock_compiled_module.dump_state.return_value = {
        "main_predictor": {
            "signature": {
                "instructions": "MIPROv2 Optimized instructions.",
                "fields": [],
            },
            "train": [{"input_a": "A", "output_c": "C"}],
            "traces": [],
            "demos": [],
            "lm": None,
        }
    }
    mock_optimizer.compile.return_value = mock_compiled_module
    mock_miprov2.return_value = mock_optimizer

    compile_and_save_agent(payload)

    from sift.modules.agents.metric import dynamic_api_metric
    mock_miprov2.assert_called_once_with(num_candidates=2, metric=dynamic_api_metric)
    mock_save_agent.assert_called_once()


@patch("sift.modules.agents.repository.langfuse.save_agent")
def test_compile_and_save_agent_invalid_optimizer(mock_save_agent):
    payload = {
        "agent_name": "test-agent",
        "agent_card_params": {},
        "litellm_params": {"model": "openai/gpt-4o-mini"},
        "dspy_params": {
            "optimizer": "FakeOptimizer",
            "state": {
                "main_predictor": {
                    "signature": {
                        "instructions": "Original instructions.",
                        "fields": [
                            {"name": "input_a", "json_schema_extra": {"__dspy_field_type": "input"}},
                            {"name": "output_c", "json_schema_extra": {"__dspy_field_type": "output"}},
                        ],
                    },
                    "train": [{"input_a": "A", "output_c": "C"}],
                    "traces": [],
                    "demos": [],
                }
            }
        },
    }

    import pytest
    with pytest.raises(ValueError, match="Optimizer FakeOptimizer not found in dspy.teleprompt"):
        compile_and_save_agent(payload)

    mock_save_agent.assert_not_called()


@patch("sift.modules.agents.repository.langfuse.save_agent")
def test_compile_and_save_agent_infers_fields(mock_save_agent):
    payload = {
        "agent_name": "test-agent",
        "agent_card_params": {},
        "litellm_params": {"model": "openai/gpt-4o-mini"},
        "dspy_params": {
            "state": {
                "main_predictor": {
                    "signature": {
                        "instructions": "",
                        "fields": [],
                    },
                    "train": [{"question": "Q", "answer": "A", "metadata": "ignored"}],
                    "traces": [],
                    "demos": [],
                }
            }
        },
    }

    compile_and_save_agent(payload)

    mock_save_agent.assert_called_once()
    saved_agent = mock_save_agent.call_args[0][0]
    pred_state = saved_agent.dspy_params.state["main_predictor"]

    fields = pred_state.signature.fields
    assert len(fields) == 3
    names = [f["name"] for f in fields]
    assert "question" in names
    assert "answer" in names
    assert "metadata" in names

    for f in fields:
        extra = f["json_schema_extra"]
        if f["name"] == "answer":
            assert extra["__dspy_field_type"] == "output"
        else:
            assert extra["__dspy_field_type"] == "input"
